### ISSUE TITLE
Retain cycle

### ISSUE THREAD

**Issue by edwardean** [zwaldowski/BlocksKit#317]
UIControl+BlocksKit and UIGestureRecognizer+BlocksKit may be mayLead to Retain cycle.

For example：
        self.senderButton = [UIButton buttonWithType:UIButtonTypeCustom];
        [self.senderButton bk_addEventHandler:^(id sender) {
            [self buttonTapped];
        } forControlEvents:UIControlEventTouchUpInside];
        [self.view addSubView:self.senderButton];

**Comment by zwaldowski** [comment]
This is by design, it's how blocks work. What would you expect it to do? I recommend rereading [Working with Blocks](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/WorkingwithBlocks/WorkingwithBlocks.html#//apple_ref/doc/uid/TP40011210-CH8-SW16) in the Objective-C Programming Guide.
